# Generated by Django 5.2 on 2025-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_contactmessage_alter_category_created_at_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_subscription_active',
            field=models.BooleanField(default=False, verbose_name='Abonnement actif'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin d'abonnement"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('small', 'Small - 7 produits'), ('medium', 'Medium - 20 produits'), ('large', 'Large - Illimité')], default='small', max_length=10, verbose_name="Plan d'abonnement"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date de début d'abonnement"),
        ),
    ]
